[package]
name = "rusteriser"
version = "0.1.0"
authors = ["Adam Wolski <miniukof@gmail.com>"]

[dependencies]

log = '*'
env_logger = '*'
sdl2 = '*'
tobj = '*'
cgmath = '0.9.1'
image = {version = '*', default-features = false, features = ["png_codec", "tga"]}
rand = '*'
